language: ruby
dist: trusty
sudo: false
bundler_args: --without yard guard benchmarks
script: "bundle exec rake spec"
cache: bundler
rvm:
  - 2.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
matrix:
  include:
    - rvm: jruby-9.1.7.0
      env: JRUBY_OPTS="$JRUBY_OPTS --debug --2.0"  # for simplecov
      before_install: gem install bundler --no-ri --no-rdoc
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug --2.0"  # for simplecov
      before_install: gem install bundler --no-ri --no-rdoc
    - rvm: rbx-3
      before_install: gem update bundler
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-3
    - rvm: ruby-head
  fast_finish: true
